spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
