spring:
  batch:
    job:
#      names: ${job.name:NONE}
#      names: "helloWorldJob"
#      names: "validatedParamJob"
#      names: "jobListenerJob"
#      names: "trMigrationJob"
#      names: "conditionalStepJob"
      names: "multipleStepJob"
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
